### ISSUE TITLE
UltraSnaffler does not quit after execution

### ISSUE THREAD

**Issue by cmprmsd** [SnaffCon/Snaffler#52]
It seems the tool keeps running, when I give it a PathTarget. I see utilization in the tool for some while and output on the test-path. But after a while it stops and does not use any resources but also does not quit with a "I'm done" message.

Might this be caused by a config clash?

I also noticed you quadruple escape backslashes now in UltraSnaffler and some rules have additional parameters e.g.:
```toml
# Snaffler
WordList = ["\\print$", "\\ipc$"]
# vs UltraSnaffler
WordList = ["\\\\{2}print\\$", "\\\\{2}ipc\\$"]
```
Two example configurations would be awesome to be added to the repository, as the `-z generate` does not include comments and therefore unused parameters when generated.
