### ISSUE TITLE
Some ClassifierRules shadow other ClassifierRules

### ISSUE THREAD

**Issue by cmprmsd** [SnaffCon/Snaffler#53]
It seems that I can't just add the German ClassifierRules behind the default classifier ruleset as the matching will not happen then.
```toml
[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "KeepGermanFilenameRegexRed"
MatchAction = "Snaffle"
Description = "Files with these file name patterns are very interesting in German companies."
MatchLocation = "FileName"
WordListType = "Regex"
MatchLength = 0
WordList = ["(Kenn|Pass)w[oö]rte?r?", "Schlüssel", "Zug[aä]ng[es]?", "T[oü]r[ -]?Code", "PINs?\\.", "Kont(o|en)", "Logindaten", "Anmeld(edaten|ung)"]
Triage = "Red"
```

I iterated through the rules and noticed the following rule to be the issue:

```toml
[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "ConfigContentByExt"
MatchAction = "Relay"
RelayTarget = "KeepConfigRegexRed"
Description = "Files with these extensions will be subjected to a generic search for keys and such."
MatchLocation = "FileExtension"
WordListType = "Exact"
MatchLength = 0
WordList = ["\\.yaml", "\\.yml", "\\.toml", "\\.xml", "\\.json", "\\.config", "\\.ini", "\\.inf", "\\.cnf", "\\.conf", "\\.properties", "\\.env", "\\.dist", "\\.txt", "\\.sql", "\\.log", "\\.sqlite", "\\.sqlite3", "\\.fdb"]
Triage = "Green"
[[ClassifierRules]]
EnumerationScope = "ContentsEnumeration"
RuleName = "KeepConfigRegexRed"
MatchAction = "Snaffle"
Description = "A description of what a rule does."
MatchLocation = "FileContentAsString"
WordListType = "Regex"
MatchLength = 0
WordList = ["sqlconnectionstring\\s*=\\s*[\\'\\\"][^\\'\\\"]....", "connectionstring\\s*=\\s*[\\'\\\"][^\\'\\\"]....", "validationkey\\s*=\\s*[\\'\\\"][^\\'\\\"]....", "decryptionkey\\s*=\\s*[\\'\\\"][^\\'\\\"]....", "passwo?r?d\\s*=\\s*[\\'\\\"][^\\'\\\"]....", "CREATE (USER|LOGIN) .{0,200} (IDENTIFIED BY|WITH PASSWORD)", "(xox[pboa]-[0-9]{12}-[0-9]{12}-[0-9]{12}-[a-z0-9]{32})", "https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}", "aws[_\\-\\.]?key", "[_\\-\\.]?api[_\\-\\.]?key", "[_\\-\\.]oauth\\s*=", "client_secret", "secret[_\\-\\.]?(key)?\\s*=", "-----BEGIN( RSA| OPENSSH| DSA| EC| PGP)? PRIVATE KEY( BLOCK)?-----", "(\\s|\\'|\\\"|\\^|=)(A3T[A-Z0-9]|AKIA|AGPA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}(\\s|\\'|\\\"|$)", "NVRAM config last updated", "enable password \\.", "simple-bind authenticated encrypt"]
Triage = "Red"
```

Moving the German ClassifierRules above the mentioned extension rule will result in the files being discovered.

I also found out that it will find the files if I give the german test files another extension e.g. 
![image](https://user-images.githubusercontent.com/73472903/129553136-03524295-700d-4c35-88b0-482c616d0a99.png)

Why does the scanner stop after the first classifier matches? I think it's important to also apply the upfollowing rules as without it all the .txt files with juicy names will not be discovered.
