### ISSUE TITLE
UltraSnaffler Dependencies

### ISSUE THREAD

**Issue by cmprmsd** [SnaffCon/Snaffler#84]
Heyhey!

I updated since a while and now see that UltraSnaffler is not working any more :cry: 

From what I see your added a local dependency AlphaFS from your local Group3r repo:
https://github.com/SnaffCon/Snaffler/commit/20cbe337b5ebf9679801e54b44233211e4ee8d28

I tried cloning and compiling grouper in the same folder level where Snaffler is located, but it does not work.
Compilation errors in Group3r:
![image](https://user-images.githubusercontent.com/73472903/151693078-1c50cbc9-f05d-4ee1-8930-039897e2a18e.png)

So I installed AlphaFS from Nuget (2.2.6) for Snaffler and UltraSnaffler in the UltrtaSnaffler solution and am left with the error on the bottom of this image:
![image](https://user-images.githubusercontent.com/73472903/151693161-e585c64a-2e97-45c4-98d1-be7ae876c271.png)

Note. Snaffler itself compiles fine :) 

Edit:
I just had a more in depth look and it seems UltraSnaffler does not like the new way of checking permissions. 
I removed all RwStatus related stuff and it compiles. Of course now it does lack all permission checks. :sweat_smile:

**Comment by l0ss** [comment]
yeah i'm pretty sure that's what i did in snaffler itself too. I'm working on a better way inside group3r but i'm not sure when i'll bring it over to snaffler. AlphaFS should have been removed as it's no longer used by snaffler.

**Comment by cmprmsd** [comment]
Heyho,

Not sure how to pull request this, without messing up the project (Visual Studio is a bitch)

Got the newrules branch working with UltraSnaffler by doing the following changes. I only tested it locally at this moment. Have to check on network shares.

* Remove all content from `EffectiveAccess.cs` in UltraSnaffler solution and insert the following:
```csharp
namespace SnaffCore.Classifiers.EffectiveAccess
{
    public class RwStatus
    {
        public bool CanRead { get; set; }
        public bool CanWrite { get; set; }
        public bool CanModify { get; set; }
    }

}
```

* Remove the AlphaFS entry in References
* Remove the missing <defaultRules>.cs files

**Comment by cmprmsd** [comment]
For the new toml files of course a relay target for content search has to be added:
```toml
[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "OfficeContentByExt"
MatchAction = "Relay"
RelayTargets = ["KeepOfficeRegexRed"]
Description = "Files with these extensions will be searched for sensitive strings."
MatchLocation = "FileExtension"
WordListType = "Exact"
MatchLength = 0
WordList = ["\\.xls", "\\.xlt", "\\.xlsx", "\\.xlst", "\\.doc", "\\.docx", "\\.dotx", "\\.rtf", "\\.eml", "\\.msg", "\\.pdf", "\\.accdb"]
Triage = "Green"
```
with some very important strings that you want to find in your `KeepOfficeRegexRed` toml file :)
